//////////////////////////////////////////////////////////////////////////////
//
// This file is part of the Corona game engine.
// For overview and more information on licensing please refer to README.md
// Home page: https://github.com/coronalabs/corona
// Contact: support@coronalabs.com
//
//////////////////////////////////////////////////////////////////////////////

#pragma once

#include "Core\Rtt_Build.h"
#include "Rtt_PlatformTimer.h"
#include <Windows.h>
#include <unordered_map>
#include <atomic>

/// <summary>
///  Custom window message posted by WinTimer's pacing path to the main thread.
///  Used to trigger a Corona runtime tick (Evaluate + render) safely on the main
///  thread, since the Lua runtime is not thread-safe.
///  Unlike WM_TIMER which is generated by Windows only when the queue is idle,
///  this message is gated by fTickPending to prevent queue flooding under load.
/// </summary>
#define WM_CORONA_TIMER (WM_USER + 0x100)

namespace Rtt
{

	class WinTimer : public PlatformTimer
	{
		Rtt_CLASS_NO_COPIES(WinTimer)

	public:
		/// <summary>Creates a new Win32 timer.</summary>
		/// <param name="callback">The callback to be invoked every time the timer elapses.</param>
		/// <param name="windowHandle">Handle to a window or control to attach the Windows timer to. Can be null.</param>
		WinTimer(MCallback& callback, HWND windowHandle);

		/// <summary>Destroys the timer and its resources. Stops the timer if currently running.</summary>
		virtual ~WinTimer();

		/// <summary>Starts the timer.</summary>
		virtual void Start() override;

		/// <summary>Stops the timer, if running.</summary>
		virtual void Stop() override;

		/// <summary>Sets the timer's interval in milliseconds. This can be applied while the timer is running.</summary>
		virtual void SetInterval(U32 milliseconds) override;

		/// <summary>Determines if the timer is currently running.</summary>
		virtual bool IsRunning() const override;

		/// <summary>
		///  Invokes the timer callback if the current timing path says it is due.
		///  The threaded pacing path has already enforced the interval before posting
		///  WM_CORONA_TIMER, while the legacy WM_TIMER path re-checks the interval here.
		/// </summary>
		void Evaluate();

		/// <summary>
		///  Records that the main thread has reached a new frame boundary and that
		///  pacing should restart from the current time.
		/// </summary>
		void SignalFrameBoundary();

	private:
		/// <summary>
		///  Static entry point for the pacing background thread.
		/// </summary>
		static DWORD WINAPI TimerThreadProc(LPVOID lpParam);

		/// <summary>
		///  Main loop for the pacing background thread. Used for lower frame-rate
		///  pacing modes that still need a delayed wake-up after a frame boundary.
		/// </summary>
		void ThreadLoop();

		/// <summary>
		///  Called by Windows when the legacy system timer has elapsed.
		///  Calls WinTimer's Evaluate() function to see if it is time to invoke its callback.
		/// </summary>
		static VOID CALLBACK OnTimerElapsed(HWND hwnd, UINT uMsg, UINT_PTR idEvent, DWORD dwTime);

		/// <summary>
		///  Compares the given tick values returned by ::GetTickCount().
		///  Correctly handles tick overflow where large negative numbers are considered
		///  greater than large positive numbers.
		/// </summary>
		static S32 CompareTicks(S32 x, S32 y);

		HWND fWindowHandle;

		/// <summary>
		///  Background thread handle for the pacing loop.
		///  Only valid when fUseThreadedScheduler is true and the timer is running.
		/// </summary>
		HANDLE fThreadHandle;

		/// <summary>
		///  Event signaled by Stop() to request the background thread to exit cleanly.
		/// </summary>
		HANDLE fStopEvent;

		/// <summary>
		///  Event signaled whenever the main thread reaches a new frame boundary.
		/// </summary>
		HANDLE fFrameBoundaryEvent;

		/// <summary>
		///  Indicates whether the timer is currently running.
		///  Declared volatile because it is written by the main thread (Start/Stop)
		///  and read by the background thread (ThreadLoop()).
		/// </summary>
		volatile bool fRunning;

		/// <summary>
		///  True if the paced thread/message path is active.
		///  Falls back to false for legacy WM_TIMER behavior when there is no
		///  window handle available for WM_CORONA_TIMER delivery.
		/// </summary>
		bool fUseThreadedScheduler;

		/// <summary>
		///  True when the timer should immediately queue the next WM_CORONA_TIMER from
		///  the frame boundary itself, letting vsync/present completion be the clock.
		/// </summary>
		bool fUseImmediateScheduler;

		// Legacy WM_TIMER fallback members — only used when fUseThreadedScheduler is false.
		UINT_PTR fTimerPointer;
		UINT_PTR fTimerID;
		U32 fIntervalInMilliseconds;
		S32 fNextIntervalTimeInTicks;
		std::atomic<LONGLONG> fLastFrameBoundaryQpc;

	public:
		/// <summary>
		///  Maps timer IDs to their WinTimer instances.
		///  Used by both the legacy WM_TIMER callback (OnTimerElapsed) and the
		///  paced WM_CORONA_TIMER path (RenderSurfaceControl) to look up the
		///  correct WinTimer from a posted message's wParam.
		/// </summary>
		static std::unordered_map<UINT_PTR, WinTimer*> sTimerMap;

		/// <summary>
		///  Incrementing counter used to generate unique timer IDs.
		/// </summary>
		static UINT_PTR sMostRecentTimerID;

		/// <summary>
		///  Atomic flag used to gate WM_CORONA_TIMER delivery between the pacing
		///  thread and the main thread.
		///  Set to true by ThreadLoop() immediately before posting WM_CORONA_TIMER.
		///  Cleared back to false by SignalFrameBoundary() after the callback has
		///  completed and pacing has been re-anchored to the new frame boundary.
		///  ThreadLoop() only posts a new message when this flag is false, ensuring
		///  at most one WM_CORONA_TIMER is in flight at any time.
		/// </summary>
		std::atomic<bool> fTickPending;
	};

}	// namespace Rtt
