<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets">
    <Import Project="Lua.Library.Externals.props" />
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <OutDir>$(Configuration)\$(Platform)\$(ProjectName)\</OutDir>
    <IntDir>$(Configuration)\$(Platform)\$(ProjectName)\</IntDir>
    <TargetName>lua</TargetName>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;_USRDLL;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
    <PostBuildEvent>
      <Command>
   REM Digitally sign the application.
   if $(ConfigurationName) == Release (
      call "$(SolutionDir)Build.Tools\CoronaLabsInc.Sign.bat" "$(TargetPath)"
   )

   mkdir "$(SolutionDir)Bin\Lua"
   copy /y "$(TargetPath)" "$(SolutionDir)Bin\Lua"

   mkdir "$(SolutionDir)Bin\Corona"
   copy /y "$(TargetPath)" "$(SolutionDir)Bin\Corona"

</Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>
