//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Simulator.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_SIMULATOR_MENU              128
#define IDR_ACTIVEWND                   129
#define IDS_INVALID_NXS_APP_VERSION_NUMBER 132
#define IDD_PASSWORD                    316
#define IDD_MESSAGE                     317
#define IDD_PREFERENCES                 334
#define IDD_NEW_PROJECT                 349
#define IDD_RELAUNCH_PREF               375
#define IDD_HTML_MESSAGE                379
#define IDS_OPENMAINLUA                 501
#define IDS_ONLYMAINLUA                 502
#define IDS_EXPIRE                      503
#define IDS_HARDWARE_SUSPEND            504
#define IDS_RESUME                      505
#define IDS_HARDWARE_RESUME             506
#define IDS_CHOOSEFOLLOWING             509
#define IDS_CONSOLE_FAILED              530
#define IDS_CONSOLE_FREE                531
#define IDS_DIR_s_NOTFOUND_INSTALL      532
#define IDS_FILE_s_NOTFOUND_INSTALL     533
#define IDS_QUIT                        535
#define IDS_CONTINUE                    536
#define IDS_OK                          538
#define IDS_DOWNLOAD                    540
#define IDS_CANCEL                      541
#define IDS_REMOVE_s_APPDIR             542
#define IDS_DONE                        544
#define IDS_VIEW_EXPLORER               545
#define IDS_INSTALLNOW                  547
#define IDS_COULDNOTLOAD_s_ERR_d        548
#define IDS_FUNCTION_s_IN_s             549
#define IDS_APPCORRUPTED                550
#define IDS_CONNECTINGTOSERVER          582
#define IDS_CONSOLE_CREATE              583
#define IDS_NO_INTERNET                 584
#define IDS_UNKNOWNERROR                585
#define IDS_ASSOCLUA                    589
#define IDS_OPENPROJECTINEDITOR         590
#define IDS_OPENGL_VERSION_WARNING      605
#define IDS_WARNING                     606
#define IDS_UNKNOWN                     607
#define IDS_IGNORE                      623
#define IDS_SIMULATOR_FILES             650
#define IDS_REMIND_ME_LATER             655
#define IDS_OPENGL21_VERSION_WARNING    664
#define IDC_LINK_ANSCAMOBILE            1000
#define IDC_KEY                         1015
#define IDC_PASSWORD                    1016
#define IDC_SAVEPASSWORD                1017
#define IDC_MSG_ICON                    1025
#define IDC_MSG_TEXT                    1026
#define IDC_ABOUT_VERSION               1027
#define IDC_ANSCALOGO                   1041
#define IDC_COMMAND1                    1042
#define ID_MSG_BUTTON2                  1049
#define ID_MSG_BUTTON3                  1050
#define IDC_COPYRIGHT                   1052
#define IDC_PICTURE_BOX                 1054
#define IDC_PICTURE_FRAME               1054
#define IDC_APP_NAME_LABEL              1056
#define IDC_APP_NAME_EDIT_BOX           1057
#define IDC_TEMPLATE_GROUP_BOX          1058
#define IDC_TEMPLATE_BLANK              1059
#define IDC_TEMPLATE_TAB_BAR            1060
#define IDC_TEMPLATE_GAME               1061
#define IDC_TEMPLATE_EBOOK              1062
#define IDC_SCREEN_SIZE_GROUP_BOX       1064
#define IDC_SCREEN_SIZE_COMBO_BOX       1065
#define IDC_SCREEN_WIDTH_LABEL          1066
#define IDC_SCREEN_WIDTH_EDIT_BOX       1067
#define IDC_SCREEN_HEIGHT_LABEL         1068
#define IDC_SCREEN_HEIGHT_EDIT_BOX      1069
#define IDC_APP_LOCATION_LABEL          1071
#define IDC_APP_LOCATION_EDIT_BOX       1072
#define IDC_BROWSE_BUTTON               1073
#define IDC_TEMPLATE_BLANK_LABEL        1076
#define IDC_DIVIDING_LINE               1077
#define IDC_TEMPLATE_TAB_BAR_LABEL      1078
#define IDC_TEMPLATE_GAME_LABEL         1079
#define IDC_TEMPLATE_EBOOK_LABEL        1080
#define IDC_FILTER_COMBO_BOX            1084
#define IDC_USER_ACCOUNT                1086
#define IDC_CHECK1                      1091
#define IDC_REMEMBER_PREF               1092
#define IDC_CD_DEVICE_NAME              1093
#define IDC_CD_SCREEN_WIDTH             1094
#define IDC_CD_SCREEN_HEIGHT            1095
#define IDC_WEB_BROWSER                 1100
#define IDC_CD_PLATFORM                 1102
#define ID_Menu                         32771
#define ID_FILE_RELAUNCH                32774
#define ID_VIEW_SUSPEND                 32778
#define ID_HELP_HELP                    32779
#define ID_WINDOW_VIEWAS                32782
#define ID_WINDOW_VIEWING               32783
#define ID_FILE_SHOWPROJECTSANDBOX      32796
#define ID_FILE_OPENINEDITOR            32799
#define ID_VIEW_DEMO                    32801
#define ID_FILE_OPENINWINDOWSEXPLORER   32809
#define ID_FILE_SHOW_PROJECT_FILES      32810
#define ID_VIEW_VIEWAS                  32814
#define ID_VIEWAS_                      32815
#define ID_VIEWAS_PLACEHOLDER           32816
#define ID_VIEW_NAVIGATE_BACK           32817
#define ID_FILE_CLEARPROJECTSANDBOX     32818
#define ID_VIEWAS_BEGIN                 32900
#define ID_VIEWAS_END                   32999

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        383
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           382
#endif
#endif
