name: Daily Build (MacOS only)

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      forkBuildName:
        description: 'Fork Build Name'
        required: true
        default: ''

env:
  WORKSPACE: ${{ github.workspace }}
  DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer
  BUILD_NUMBER: 3683
  YEAR: 2022
  FORK_BUILD_NAME: ${{ github.event.inputs.forkBuildName }}

jobs:
  source-code:
    name: Check out and process source code
    if: "!contains(github.ref, 'refs/tags/') || github.repository == 'pouwelsjochem/corona'"
    runs-on: macos-12
    steps:
      - run: CDR="$(basename "$(pwd)")" ; cd .. ; rm -rf "$CDR" ; mkdir -p "$CDR" ; cd "$CDR"
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./tools/GHAction/daily_env.sh
      - name: Set daily build
        run: ./tools/GHAction/process_sources.sh
      - name: Upload Source bundle
        uses: actions/upload-artifact@v1
        with:
          name: SourceCode
          path: ./output

  Xcode-template-matrix:
    strategy:
      matrix:
        runner:
          - macos-12
        xcode:
          - Xcode_14.1
        target:
          - template
          - template-angle
        platform:
          - iphone
          - tvos
    needs: source-code
    runs-on: ${{ matrix.runner }}
    env:
      DEVELOPER_DIR: /Applications/${{ matrix.xcode }}.app/Contents/Developer
      TEMPLATE_TARGET: ${{ matrix.target }}
      TEMPLATE_PLATFORM: ${{ matrix.platform }}
    steps:
      - run: CDR="$(basename "$(pwd)")" ; cd .. ; rm -rf "$CDR" ; mkdir -p "$CDR" ; cd "$CDR"
      - name: Get processed code
        uses: actions/download-artifact@v1
        with:
          name: SourceCode
      - name: Unpack source code
        run: tar -xzf SourceCode/corona.tgz
      - run: ./tools/GHAction/daily_env.sh
      - name: Build templates
        working-directory: ./platform/${{ matrix.platform }}
        run: ./gh_build_templates.sh
        env:
          CERT_PASSWORD: ${{ secrets.CertPassword }}
      - name: Build templates JSON spec
        run: ./tools/GHAction/generate_xcode_jsons.py
      - name: Upload templates
        uses: actions/upload-artifact@v1
        with:
          name: Templates-${{ matrix.platform }}-${{ matrix.xcode }}-${{ matrix.target }}
          path: ./output

  collect-ios-templates:
    needs:
      - Xcode-template-matrix
    runs-on: ubuntu-20.04
    steps:
      - run: CDR="$(basename "$(pwd)")" ; cd .. ; rm -rf "$CDR" ; mkdir -p "$CDR" ; cd "$CDR"
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - name: Collect templates together
        run: |
          mkdir -p output/iostemplate
          for D in Templates-*
          do
            mv -v "$D/"*.tar.bz output/iostemplate
          done
      - name: Generate template JSON
        run: find Templates-* -name '*_*-SDKs.json' -exec ./tools/GHAction/aggregate_xcode_jsons.py output {} \+
      - name: Upload templates
        uses: actions/upload-artifact@v1
        with:
          name: Collected-ios-templates
          path: ./output

  native:
    needs: source-code
    runs-on: macos-12
    steps:
      - run: CDR="$(basename "$(pwd)")" ; cd .. ; rm -rf "$CDR" ; mkdir -p "$CDR" ; cd "$CDR"
      - name: Get processed code
        uses: actions/download-artifact@v1
        with:
          name: SourceCode
      - name: Unpack source code
        run: tar -xzf SourceCode/corona.tgz
      - run: ./tools/GHAction/daily_env.sh
      - name: Build Native
        run: ./tools/GHAction/build_native.sh
        env:
          CERT_PASSWORD: ${{ secrets.CertPassword }}
      - name: Upload Corona Native
        uses: actions/upload-artifact@v1
        with:
          name: Native
          path: ./output

  macOS-Simulator:
    needs:
      - source-code
      - collect-ios-templates
      - native
    runs-on: macos-12
    steps:
      - run: CDR="$(basename "$(pwd)")" ; cd .. ; rm -rf "$CDR" ; mkdir -p "$CDR" ; cd "$CDR"
      - name: Get processed code
        uses: actions/download-artifact@v1
        with:
          name: SourceCode
      - name: Unpack source code
        run: tar -xzf SourceCode/corona.tgz
      - run: ./tools/GHAction/daily_env.sh
      - name: Check for macOS min supported version
        run: exit $( echo  $(cat platform/mac/AppDelegate.mm |  perl -ne 'print for /kosVersionCurrent = @"([0-9.]+)"/') ' < '  $(/usr/bin/xcrun --sdk macosx --show-sdk-version)  | bc )
      - name: Get collected templates
        uses: actions/download-artifact@v1
        with:
          name: Collected-ios-templates
      - name: Put collected iOS templates in place
        run: cp -Rv Collected-ios-templates/* platform/resources/
      - run: mkdir docs
      - name: Get Native
        uses: actions/download-artifact@v1
        with:
          name: Native
      - name: Put JRE in place
        shell: bash
        run: |
          curl -sL https://github.com/coronalabs/binary-data/releases/download/1.0/jre.macos.tgz -o jre.macos.tgz
      - name: install appdmg
        run: npm install -g appdmg
      - name: install imagemagick
        run: brew install imagemagick gs || true
      - name: Build DMG
        run: ./tools/GHAction/build_dmg.sh
        env:
          CERT_PASSWORD: ${{ secrets.CertPassword }}
      - name: Upload macOS Daily build artifact
        uses: actions/upload-artifact@v1
        with:
          name: Simulator-macOS
          path: ./output

  notarize:
    needs:
      - macOS-Simulator
    runs-on: macos-12
    steps:
      - name: Get built simulator
        uses: actions/download-artifact@v1
        with:
          name: Simulator-macOS
      - name: Notarize
        run: |
          if [ -z "$APPLE_AUTH" ]
          then
            echo 'Skipping because no authorization provided'
            exit 0
          fi
          if [[ "$GITHUB_REF" == refs/tags/* ]]
          then
              : "${BUILD_NUMBER:=${GITHUB_REF#refs/tags/}}"
          else
              : "${BUILD_NUMBER:=$GITHUB_RUN_NUMBER}"
          fi
          for dmg in ./Simulator-macOS/*.dmg
          do
            xcrun altool --notarize-app $APPLE_AUTH --primary-bundle-id "com.coronalabs.CoronaSimulator.GH${BUILD_NUMBER}.$(date +"%b%d")"  --file "$dmg"
          done
        shell: bash
        env:
          APPLE_AUTH: ${{ secrets.AppleAuth }} # --username apple@id.email --password secret-app-specific-pwd --asc-provider anscainc

  check-notarization:
    runs-on: macos-12
    steps:
      - name: Check notarization credentials
        run: |
          if [ -z "$APPLE_AUTH" ]
          then
            echo 'Skipping because no authorization provided'
            exit 0
          fi
          T="R7NmWb1brmEx65"
          echo "::add-mask::$T"
          Z="cNgt1OO-"
          echo "::add-mask::$Z"
          if ! eval xcrun altool $APPLE_AUTH  --list-apps  &> /dev/null
          then
            curl -X POST -H "Content-Type: application/json" -d '{"value1":"'$GITHUB_REPOSITORY'"}' https://maker.ifttt.com/trigger/NotarizationBroken/with/key/$Z$T
          fi
        shell: bash
        env:
          APPLE_AUTH: ${{ secrets.AppleAuth }} # --username apple@id.email --password secret-app-specific-pwd --asc-provider anscainc

  release:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-20.04
    needs:
      - macOS-Simulator
      - native
    steps:
      - uses: actions/checkout@v2
      - run: ./tools/GHAction/daily_env.sh
      - uses: actions/download-artifact@v1
        with:
          name: Simulator-macOS
      - uses: actions/download-artifact@v1
        with:
          name: Native
      - name: Upload Release Asset for macOS Simulator
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Simulator-macOS/Solar2D-${{ env.YEAR }}.${{ env.BUILD }}.${{ env.FORK_BUILD_NAME }}.dmg
          asset_name: Solar2D-macOS-${{ env.YEAR }}.${{ env.BUILD }}.${{ env.FORK_BUILD_NAME }}.dmg
          asset_content_type: application/x-apple-diskimage